<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hexa_gen_help($route_name, RouteMatchInterface $routeMatchInterface)
{
	switch ($route_name) {
		case 'help.page.hexa_gen':
			return t('
				<h3>Acerca de</h3>
				<p>Acá puedes agregar el color en hexadecimal</p>
			');

			break;
	}
}

/**
 * Implements hook_theme().
 */
function hexa_gen_theme()
{
	return [
		'color hexadecimal' => [
			'variables' => [
				'title' => '',
				'color' => ''
			],
			'template' => 'hexa_gen'
		]
	];
}

?>